repos:
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      args: [--line-length=88, --safe]
      exclude: ^(setup\.py$|doc)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: debug-statements
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    - id: flake8
      exclude: ^(setup\.py$|static_tests|doc|fastentrypoints.py)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
    - id: mypy
      args: [--no-incremental]
      files: ^.*\.py$
      exclude: ^(setup\.py$|test|fastentrypoints.py|Documentation/conf.py)
-   repo: local
    hooks:
    - id: tests
      name: Run rbot selftest and regression test-suite
      language: system
      entry: python3 -m pytest test/
      files: ^.*\.py$
      pass_filenames: false
